### ISSUE TITLE
Missing translations for breadcrumb menu items

### ISSUE THREAD

**Issue by covex-nn** [sonata-project/media-orm-pack#3]
I've just tested a recipe for a new media-orm-pack. Everything works as expected, except one: if a last part of class name for Media or Gallery differs from `Media` and `Gallery`, then breadcrumb will contain some non-translated strings like `breadcrumb.link_sonata_media_media_list` or `breadcrumb.link_sonata_media_media_create`.

Future pack configuration, as an example:

```yaml
sonata_media:
    class:
        media: App\Entity\SonataMediaMedia
        gallery: App\Entity\SonataMediaGallery
        gallery_has_media: App\Entity\SonataMediaGalleryHasMedia
    db_driver: doctrine_orm
```

There are 4 ways how to fix issue:

1. Rename entity classes to `App\Entity\Media` and etc., but i guess it is too generic and not unique. If that files exist, Flex will not override them during installation process.
2. Duplicate translation strings like `breadcrumb.link_media_create` in `src/Resources/translations/SonataMediaBundle.*.xliff`. But copy-paste it is not good, i guess.
3. Create `translations/SonataMediaBundle.en.xliff` file for recipe and copy it with configuration and entity classes. This is copy-paste too, but here we do not have to support. But it looks weird )
4. Add `protected $classnameLabel = 'Media';` to `Sonata\MediaBundle\Admin\BaseMediaAdmin`. Then `Sonata\AdminBundle\Admin\BreadcrumbsBuilder` in [createMenuItem](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/BreadcrumbsBuilder.php#L150) method will use already translated strings: `breadcrumb.link_media_list` or `breadcrumb.link_media_create`.

How do you think, which way is better? I like the last one more.
